#!/bin/zsh

iptables='/usr/bin/iptables'
iptabsave='/usr/bin/iptables-save'

# flush
$iptables -F
$iptables -X
$iptables -Z

# default policy -> DROP

$iptables -P INPUT DROP
$iptables -P OUTPUT ACCEPT
$iptables -P FORWARD DROP

$iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
$iptables -i lo -j ACCEPT
$iptables -m conntrack --ctstate INVALID -j DROP
$iptables -A INPUT -p icmp -m icmp --icmp-type 8 -m conntrack --ctstate NEW -j ACCEPT
$iptables -A INPUT -p udp -m conntrack --ctstate NEW -j UDP
$iptables -A INPUT -p tcp --tcp-flags FIN,SYN,RST,ACK SYN -m conntrack --ctstate NEW -j TCP
$iptables -A INPUT -p udp -j REJECT --reject-with icmp-port-unreachable
$iptables -A INPUT -p tcp -j REJECT --reject-with tcp-reset
$iptables -A INPUT -j REJECT --reject-with icmp-proto-unreachable
$iptables -A INPUT -s 127.0.0.1 -p tcp --destination-port 27017 -m state --state NEW,ESTABLISHED -j ACCEPT
$iptables -A OUTPUT -d 127.0.0.1 -p tcp --source-port 27017 -m state --state ESTABLISHED -j ACCEPT
$iptables -A INPUT -s 127.0.0.1 -p tcp --source-port 19999 -m state --state NEW,ESTABLISHED -j ACCEPT

# save rules -> /etc/iptables/iptables.rules
$iptabsave > /etc/iptables/iptables.rules

# end of rules
